/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteRouteImport } from './routes/_authenticated/onboarding/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedOnboardingBusinessRouteImport } from './routes/_authenticated/onboarding/business'
import { Route as AuthenticatedOnboardingDoneRouteImport } from './routes/_authenticated/onboarding/done'
import { Route as AuthenticatedOnboardingHoursRouteImport } from './routes/_authenticated/onboarding/hours'
import { Route as AuthenticatedOnboardingProfessionalRouteImport } from './routes/_authenticated/onboarding/professional'
import { Route as AuthenticatedOnboardingServiceRouteImport } from './routes/_authenticated/onboarding/service'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsDangerRouteImport } from './routes/_authenticated/settings/danger'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsHoursRouteImport } from './routes/_authenticated/settings/hours'
import { Route as AuthenticatedSettingsTeamAndServicesRouteRouteImport } from './routes/_authenticated/settings/team-and-services/route'
import { Route as AuthenticatedSettingsTeamAndServicesIndexRouteImport } from './routes/_authenticated/settings/team-and-services/index'
import { Route as AuthenticatedSettingsTeamAndServicesProfessionalsRouteImport } from './routes/_authenticated/settings/team-and-services/professionals'
import { Route as AuthenticatedSettingsTeamAndServicesServicesRouteImport } from './routes/_authenticated/settings/team-and-services/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRouteRoute =
  AuthenticatedOnboardingRouteRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingBusinessRoute =
  AuthenticatedOnboardingBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingDoneRoute =
  AuthenticatedOnboardingDoneRouteImport.update({
    id: '/done',
    path: '/done',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingHoursRoute =
  AuthenticatedOnboardingHoursRouteImport.update({
    id: '/hours',
    path: '/hours',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingProfessionalRoute =
  AuthenticatedOnboardingProfessionalRouteImport.update({
    id: '/professional',
    path: '/professional',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingServiceRoute =
  AuthenticatedOnboardingServiceRouteImport.update({
    id: '/service',
    path: '/service',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDangerRoute =
  AuthenticatedSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsHoursRoute =
  AuthenticatedSettingsHoursRouteImport.update({
    id: '/hours',
    path: '/hours',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsTeamAndServicesRouteRoute =
  AuthenticatedSettingsTeamAndServicesRouteRouteImport.update({
    id: '/team-and-services',
    path: '/team-and-services',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsTeamAndServicesIndexRoute =
  AuthenticatedSettingsTeamAndServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsTeamAndServicesRouteRoute,
  } as any)
const AuthenticatedSettingsTeamAndServicesProfessionalsRoute =
  AuthenticatedSettingsTeamAndServicesProfessionalsRouteImport.update({
    id: '/professionals',
    path: '/professionals',
    getParentRoute: () => AuthenticatedSettingsTeamAndServicesRouteRoute,
  } as any)
const AuthenticatedSettingsTeamAndServicesServicesRoute =
  AuthenticatedSettingsTeamAndServicesServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedSettingsTeamAndServicesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings/team-and-services': typeof AuthenticatedSettingsTeamAndServicesRouteRouteWithChildren
  '/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/onboarding/done': typeof AuthenticatedOnboardingDoneRoute
  '/onboarding/hours': typeof AuthenticatedOnboardingHoursRoute
  '/onboarding/professional': typeof AuthenticatedOnboardingProfessionalRoute
  '/onboarding/service': typeof AuthenticatedOnboardingServiceRoute
  '/settings/danger': typeof AuthenticatedSettingsDangerRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/hours': typeof AuthenticatedSettingsHoursRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/team-and-services/professionals': typeof AuthenticatedSettingsTeamAndServicesProfessionalsRoute
  '/settings/team-and-services/services': typeof AuthenticatedSettingsTeamAndServicesServicesRoute
  '/settings/team-and-services/': typeof AuthenticatedSettingsTeamAndServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/onboarding/done': typeof AuthenticatedOnboardingDoneRoute
  '/onboarding/hours': typeof AuthenticatedOnboardingHoursRoute
  '/onboarding/professional': typeof AuthenticatedOnboardingProfessionalRoute
  '/onboarding/service': typeof AuthenticatedOnboardingServiceRoute
  '/settings/danger': typeof AuthenticatedSettingsDangerRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/hours': typeof AuthenticatedSettingsHoursRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/team-and-services/professionals': typeof AuthenticatedSettingsTeamAndServicesProfessionalsRoute
  '/settings/team-and-services/services': typeof AuthenticatedSettingsTeamAndServicesServicesRoute
  '/settings/team-and-services': typeof AuthenticatedSettingsTeamAndServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings/team-and-services': typeof AuthenticatedSettingsTeamAndServicesRouteRouteWithChildren
  '/_authenticated/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/_authenticated/onboarding/done': typeof AuthenticatedOnboardingDoneRoute
  '/_authenticated/onboarding/hours': typeof AuthenticatedOnboardingHoursRoute
  '/_authenticated/onboarding/professional': typeof AuthenticatedOnboardingProfessionalRoute
  '/_authenticated/onboarding/service': typeof AuthenticatedOnboardingServiceRoute
  '/_authenticated/settings/danger': typeof AuthenticatedSettingsDangerRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/hours': typeof AuthenticatedSettingsHoursRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/team-and-services/professionals': typeof AuthenticatedSettingsTeamAndServicesProfessionalsRoute
  '/_authenticated/settings/team-and-services/services': typeof AuthenticatedSettingsTeamAndServicesServicesRoute
  '/_authenticated/settings/team-and-services/': typeof AuthenticatedSettingsTeamAndServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/dashboard'
    | '/settings/team-and-services'
    | '/onboarding/business'
    | '/onboarding/done'
    | '/onboarding/hours'
    | '/onboarding/professional'
    | '/onboarding/service'
    | '/settings/danger'
    | '/settings/general'
    | '/settings/hours'
    | '/settings/'
    | '/settings/team-and-services/professionals'
    | '/settings/team-and-services/services'
    | '/settings/team-and-services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/dashboard'
    | '/onboarding/business'
    | '/onboarding/done'
    | '/onboarding/hours'
    | '/onboarding/professional'
    | '/onboarding/service'
    | '/settings/danger'
    | '/settings/general'
    | '/settings/hours'
    | '/settings'
    | '/settings/team-and-services/professionals'
    | '/settings/team-and-services/services'
    | '/settings/team-and-services'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings/team-and-services'
    | '/_authenticated/onboarding/business'
    | '/_authenticated/onboarding/done'
    | '/_authenticated/onboarding/hours'
    | '/_authenticated/onboarding/professional'
    | '/_authenticated/onboarding/service'
    | '/_authenticated/settings/danger'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/hours'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/team-and-services/professionals'
    | '/_authenticated/settings/team-and-services/services'
    | '/_authenticated/settings/team-and-services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/business': {
      id: '/_authenticated/onboarding/business'
      path: '/business'
      fullPath: '/onboarding/business'
      preLoaderRoute: typeof AuthenticatedOnboardingBusinessRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/done': {
      id: '/_authenticated/onboarding/done'
      path: '/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof AuthenticatedOnboardingDoneRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/hours': {
      id: '/_authenticated/onboarding/hours'
      path: '/hours'
      fullPath: '/onboarding/hours'
      preLoaderRoute: typeof AuthenticatedOnboardingHoursRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/professional': {
      id: '/_authenticated/onboarding/professional'
      path: '/professional'
      fullPath: '/onboarding/professional'
      preLoaderRoute: typeof AuthenticatedOnboardingProfessionalRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/service': {
      id: '/_authenticated/onboarding/service'
      path: '/service'
      fullPath: '/onboarding/service'
      preLoaderRoute: typeof AuthenticatedOnboardingServiceRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/danger': {
      id: '/_authenticated/settings/danger'
      path: '/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof AuthenticatedSettingsDangerRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/hours': {
      id: '/_authenticated/settings/hours'
      path: '/hours'
      fullPath: '/settings/hours'
      preLoaderRoute: typeof AuthenticatedSettingsHoursRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/team-and-services': {
      id: '/_authenticated/settings/team-and-services'
      path: '/team-and-services'
      fullPath: '/settings/team-and-services'
      preLoaderRoute: typeof AuthenticatedSettingsTeamAndServicesRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/team-and-services/': {
      id: '/_authenticated/settings/team-and-services/'
      path: '/'
      fullPath: '/settings/team-and-services/'
      preLoaderRoute: typeof AuthenticatedSettingsTeamAndServicesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsTeamAndServicesRouteRoute
    }
    '/_authenticated/settings/team-and-services/professionals': {
      id: '/_authenticated/settings/team-and-services/professionals'
      path: '/professionals'
      fullPath: '/settings/team-and-services/professionals'
      preLoaderRoute: typeof AuthenticatedSettingsTeamAndServicesProfessionalsRouteImport
      parentRoute: typeof AuthenticatedSettingsTeamAndServicesRouteRoute
    }
    '/_authenticated/settings/team-and-services/services': {
      id: '/_authenticated/settings/team-and-services/services'
      path: '/services'
      fullPath: '/settings/team-and-services/services'
      preLoaderRoute: typeof AuthenticatedSettingsTeamAndServicesServicesRouteImport
      parentRoute: typeof AuthenticatedSettingsTeamAndServicesRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedOnboardingRouteRouteChildren {
  AuthenticatedOnboardingBusinessRoute: typeof AuthenticatedOnboardingBusinessRoute
  AuthenticatedOnboardingDoneRoute: typeof AuthenticatedOnboardingDoneRoute
  AuthenticatedOnboardingHoursRoute: typeof AuthenticatedOnboardingHoursRoute
  AuthenticatedOnboardingProfessionalRoute: typeof AuthenticatedOnboardingProfessionalRoute
  AuthenticatedOnboardingServiceRoute: typeof AuthenticatedOnboardingServiceRoute
}

const AuthenticatedOnboardingRouteRouteChildren: AuthenticatedOnboardingRouteRouteChildren =
  {
    AuthenticatedOnboardingBusinessRoute: AuthenticatedOnboardingBusinessRoute,
    AuthenticatedOnboardingDoneRoute: AuthenticatedOnboardingDoneRoute,
    AuthenticatedOnboardingHoursRoute: AuthenticatedOnboardingHoursRoute,
    AuthenticatedOnboardingProfessionalRoute:
      AuthenticatedOnboardingProfessionalRoute,
    AuthenticatedOnboardingServiceRoute: AuthenticatedOnboardingServiceRoute,
  }

const AuthenticatedOnboardingRouteRouteWithChildren =
  AuthenticatedOnboardingRouteRoute._addFileChildren(
    AuthenticatedOnboardingRouteRouteChildren,
  )

interface AuthenticatedSettingsTeamAndServicesRouteRouteChildren {
  AuthenticatedSettingsTeamAndServicesProfessionalsRoute: typeof AuthenticatedSettingsTeamAndServicesProfessionalsRoute
  AuthenticatedSettingsTeamAndServicesServicesRoute: typeof AuthenticatedSettingsTeamAndServicesServicesRoute
  AuthenticatedSettingsTeamAndServicesIndexRoute: typeof AuthenticatedSettingsTeamAndServicesIndexRoute
}

const AuthenticatedSettingsTeamAndServicesRouteRouteChildren: AuthenticatedSettingsTeamAndServicesRouteRouteChildren =
  {
    AuthenticatedSettingsTeamAndServicesProfessionalsRoute:
      AuthenticatedSettingsTeamAndServicesProfessionalsRoute,
    AuthenticatedSettingsTeamAndServicesServicesRoute:
      AuthenticatedSettingsTeamAndServicesServicesRoute,
    AuthenticatedSettingsTeamAndServicesIndexRoute:
      AuthenticatedSettingsTeamAndServicesIndexRoute,
  }

const AuthenticatedSettingsTeamAndServicesRouteRouteWithChildren =
  AuthenticatedSettingsTeamAndServicesRouteRoute._addFileChildren(
    AuthenticatedSettingsTeamAndServicesRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsTeamAndServicesRouteRoute: typeof AuthenticatedSettingsTeamAndServicesRouteRouteWithChildren
  AuthenticatedSettingsDangerRoute: typeof AuthenticatedSettingsDangerRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsHoursRoute: typeof AuthenticatedSettingsHoursRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsTeamAndServicesRouteRoute:
      AuthenticatedSettingsTeamAndServicesRouteRouteWithChildren,
    AuthenticatedSettingsDangerRoute: AuthenticatedSettingsDangerRoute,
    AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
    AuthenticatedSettingsHoursRoute: AuthenticatedSettingsHoursRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRouteRoute: typeof AuthenticatedOnboardingRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRouteRoute:
    AuthenticatedOnboardingRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
